name: Github-actions-task
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:
      - main
jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Update dependencies
        run: pnpm update
